version: "2"

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/Westar35/site-verification)
        - blank
        - dot
    gofumpt:
      extra-rules: true
      module-path: github.com/Westar35/site-verification

issues:
  fix: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  disable:
    - dupl
    - dupword
    - err113
    - exhaustruct
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gocyclo
    - goheader
    - gomodguard
    - gosmopolitan
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - nonamedreturns
    - reassign
    - revive
    - testpackage
    - varnamelen
    - wrapcheck
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
#    - gocritic # Долго работает.
    - godot
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - grouper
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
    - zerologlint

  exclusions:
    paths:
      - gen
    rules:
      - path: _test\.go
        linters:
          - contextcheck

  settings:
    copyloopvar:
      check-alias: true

    cyclop:
      max-complexity: 30

    depguard:
      rules:
        internal:
          allow:
            # GOMOD.
            - github.com/Westar35/site-verification

            # GOROOT.
            - $gostd

            # Third-party.
            - connectrpc.com/connect
            - google.golang.org/protobuf
          files:
            - "!$test"
        main:
          deny:
            # Error.
            - pkg: github.com/pkg/errors
              desc: Instead, use "errors"
            - pkg: go.uber.org/multierr
              desc: Instead, use "errors"

            # Framework.
            - pkg: github.com/gin-gonic/gin
              desc: Instead, use ""
            - pkg: github.com/go-chi/chi
              desc: Instead, use ""
            - pkg: github.com/gofiber/fiber
              desc: Instead, use ""
            - pkg: github.com/labstack/echo
              desc: Instead, use ""

            # HTTP Router.
            - pkg: github.com/valyala/fasthttp
              desc: Instead, use "github.com/julienschmidt/httprouter"

            # JWT.
            - pkg: github.com/brianvoe/sjwt
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"
            - pkg: github.com/cristalhq/jwt
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"
            - pkg: github.com/dvsekhvalnov/jose2go
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"
            - pkg: github.com/gbrlsnchs/jwt
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"
            - pkg: github.com/gilbsgilbs/jwit
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"
            - pkg: github.com/go-jose/go-jose
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"
            - pkg: github.com/golang-jwt/jwt
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"
            - pkg: github.com/kataras/jwt
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"
            - pkg: github.com/pascaldekloe/jwt
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"
            - pkg: github.com/SermoDigital/jose
              desc: Instead, use "github.com/lestrrat-go/jwx/v3"

            # Logging.
            - pkg: github.com/sirupsen/logrus
              desc: Instead, use "log/slog"
            - pkg: github.com/rs/zerolog
              desc: Instead, use "log/slog"
            - pkg: go.uber.org/zap
              desc: Instead, use "log/slog"

            # Mock.
            - pkg: github.com/stretchr/testify/mock
              desc: Instead, use "github.com/gojuno/minimock/v3"
            - pkg: github.com/vektra/mockery
              desc: Instead, use "github.com/gojuno/minimock/v3"

            # ORM.
            - pkg: github.com/go-gorm/gorm
              desc: Instead, use ""

            # Protocol Buffers.
            - pkg: github.com/gogo/protobuf
              desc: Instead, use "google.golang.org/protobuf"
            - pkg: github.com/golang/protobuf
              desc: Instead, use "google.golang.org/protobuf"

            # PostgreSQL.
            - pkg: github.com/lib/pq
              desc: Instead, use "github.com/jackc/pgx"

            # Redis.
            - pkg: github.com/allegro/bigcache
              desc: Instead, use "github.com/redis/go-redis"
            - pkg: github.com/Code-Hex/go-generics-cache
              desc: Instead, use "github.com/redis/go-redis"
            - pkg: github.com/coocood/freecache
              desc: Instead, use "github.com/redis/go-redis"
            - pkg: github.com/microup/vcache
              desc: Instead, use "github.com/redis/go-redis"
            - pkg: github.com/patrickmn/go-cache
              desc: Instead, use "github.com/redis/go-redis"
            - pkg: github.com/redis/rueidis
              desc: Instead, use "github.com/redis/go-redis"

            # Testing.
            - pkg: github.com/go-playground/assert
              desc: Instead, use "github.com/stretchr/testify"
            - pkg: github.com/onsi/ginkgo
              desc: Instead, use "github.com/stretchr/testify"
            - pkg: github.com/onsi/gomega
              desc: Instead, use "github.com/stretchr/testify"

            # UUID.
            - pkg: github.com/gofrs/uuid
              desc: Instead, use "github.com/google/uuid"
            - pkg: github.com/rogpeppe/fastuuid
              desc: Instead, use "github.com/google/uuid"
            - pkg: github.com/satori/go.uuid
              desc: Instead, use "github.com/google/uuid"
        test:
          allow:
            # GOMOD.
            - github.com/Westar35/site-verification

            # GOROOT.
            - $gostd

            # Third-party.
            - connectrpc.com/connect
            - google.golang.org/protobuf
          files:
            - "$test"

    errcheck:
      check-blank: true
      check-type-assertions: true
      disable-default-exclusions: true
      exclude-functions:
        - (*strings.Builder).WriteString
        - crypto/rand.Read
        - encoding/json.Marshal
        - encoding/json.MarshalIndent

    errchkjson:
      check-error-free-encoding: true

    exhaustive:
      check:
        - map
        - switch

    forbidigo:
      analyze-types: true
      forbid:
        - pattern: ^((==|!=) "")$
        - pattern: ^(fmt\\.Print(|f|ln)|goto|print(|ln))$
        - pattern: ^(http\\.Default(Client|Transport))$
        - pattern: ^(time\\.Sleep)$

    gochecksumtype:
      default-signifies-exhaustive: false

    gocognit:
      min-complexity: 30

    goconst:
      ignore-calls: true
      max: 0
      min: 0
      min-len: 2
      min-occurrences: 2

    gocritic:
      disabled-checks:
        - hugeParam
        - sloppyReassign
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        # - security
        - style
      settings:
        nestingReduce:
          bodyWidth: 2
        tooManyResultsChecker:
          maxResults: 2
        truncateCmp:
          skipArchDependent: false
        underef:
          skipRecvDeref: false
        unnamedResult:
          checkExported: true

    godot:
      capital: false
      period: true
      scope: all

    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
        - OPTIMIZE

    grouper:
      import-require-grouping: true

    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true

    misspell:
      locale: US

    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
      ignored-functions:
        - make
        - strings.SplitN

    musttag:
      functions: [ ]

    nakedret:
      max-func-lines: 0

    nestif:
      min-complexity: 3

    nilnil:
      checked-types:
        - chan
        - func
        - iface
        - map
        - ptr

    nolintlint:
      require-explanation: false
      require-specific: true

    prealloc:
      for-loops: true

    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003

    tagliatelle:
      case:
        rules:
          bson: snake
          env: upperSnake
          json: snake

    usestdlibvars:
      constant-kind: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      time-layout: true
      time-month: true
      tls-signature-scheme: true

    wsl_v5:
      default: all

output:
  formats:
    text:
      colors: true
      path: stderr
      print-issued-lines: true
      print-linter-name: true
  show-stats: true
  sort-order:
    - linter
    - file

run:
  concurrency: 2
  modules-download-mode: readonly
